deployment:
  environment:
    url: https://<DEV_APP_URL>

# <ENVIRONMENT_NAME>:
#   stage: trigger
#   trigger:
#     project: <GITLAB>/<GROUP>/<PROJECT>
#     strategy: depend
#   rules:
#   - if: '$CI_COMMIT_BRANCH != "master"'
#     when: never

include:
  project: dev/ep/release-management
  file: /Jobs/EP-AutoDevops-Template.yml
